package com.alan.demo.entity;

public class Money {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.uid
     *
     * @mbg.generated Mon Mar 09 15:24:56 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.balance
     *
     * @mbg.generated Mon Mar 09 15:24:56 CST 2020
     */
    private Integer balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.uid
     *
     * @return the value of money.uid
     *
     * @mbg.generated Mon Mar 09 15:24:56 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.uid
     *
     * @param uid the value for money.uid
     *
     * @mbg.generated Mon Mar 09 15:24:56 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.balance
     *
     * @return the value of money.balance
     *
     * @mbg.generated Mon Mar 09 15:24:56 CST 2020
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.balance
     *
     * @param balance the value for money.balance
     *
     * @mbg.generated Mon Mar 09 15:24:56 CST 2020
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
}