package com.alan.demo.entity;

import java.math.BigDecimal;

public class NbaPlayer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.id
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.countryEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String countryen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.teamName
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String teamname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.birthDay
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private Long birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.country
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.teamCityEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String teamcityen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.code
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.displayAffiliation
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String displayaffiliation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.displayName
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String displayname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.schoolType
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String schooltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.teamConference
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String teamconference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.teamConferenceEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String teamconferenceen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.weight
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.teamCity
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String teamcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.playYear
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private Integer playyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.jerseyNo
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String jerseyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.teamNameEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String teamnameen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.draft
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private Integer draft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.displayNameEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String displaynameen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.birthDayStr
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String birthdaystr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.heightValue
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private BigDecimal heightvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.position
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.age
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_player.playerId
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    private String playerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.id
     *
     * @return the value of nba_player.id
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.id
     *
     * @param id the value for nba_player.id
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.countryEn
     *
     * @return the value of nba_player.countryEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getCountryen() {
        return countryen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.countryEn
     *
     * @param countryen the value for nba_player.countryEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setCountryen(String countryen) {
        this.countryen = countryen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.teamName
     *
     * @return the value of nba_player.teamName
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getTeamname() {
        return teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.teamName
     *
     * @param teamname the value for nba_player.teamName
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setTeamname(String teamname) {
        this.teamname = teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.birthDay
     *
     * @return the value of nba_player.birthDay
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.birthDay
     *
     * @param birthday the value for nba_player.birthDay
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.country
     *
     * @return the value of nba_player.country
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.country
     *
     * @param country the value for nba_player.country
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.teamCityEn
     *
     * @return the value of nba_player.teamCityEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getTeamcityen() {
        return teamcityen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.teamCityEn
     *
     * @param teamcityen the value for nba_player.teamCityEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setTeamcityen(String teamcityen) {
        this.teamcityen = teamcityen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.code
     *
     * @return the value of nba_player.code
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.code
     *
     * @param code the value for nba_player.code
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.displayAffiliation
     *
     * @return the value of nba_player.displayAffiliation
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getDisplayaffiliation() {
        return displayaffiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.displayAffiliation
     *
     * @param displayaffiliation the value for nba_player.displayAffiliation
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setDisplayaffiliation(String displayaffiliation) {
        this.displayaffiliation = displayaffiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.displayName
     *
     * @return the value of nba_player.displayName
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.displayName
     *
     * @param displayname the value for nba_player.displayName
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.schoolType
     *
     * @return the value of nba_player.schoolType
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getSchooltype() {
        return schooltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.schoolType
     *
     * @param schooltype the value for nba_player.schoolType
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setSchooltype(String schooltype) {
        this.schooltype = schooltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.teamConference
     *
     * @return the value of nba_player.teamConference
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getTeamconference() {
        return teamconference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.teamConference
     *
     * @param teamconference the value for nba_player.teamConference
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setTeamconference(String teamconference) {
        this.teamconference = teamconference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.teamConferenceEn
     *
     * @return the value of nba_player.teamConferenceEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getTeamconferenceen() {
        return teamconferenceen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.teamConferenceEn
     *
     * @param teamconferenceen the value for nba_player.teamConferenceEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setTeamconferenceen(String teamconferenceen) {
        this.teamconferenceen = teamconferenceen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.weight
     *
     * @return the value of nba_player.weight
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.weight
     *
     * @param weight the value for nba_player.weight
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setWeight(String weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.teamCity
     *
     * @return the value of nba_player.teamCity
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getTeamcity() {
        return teamcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.teamCity
     *
     * @param teamcity the value for nba_player.teamCity
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setTeamcity(String teamcity) {
        this.teamcity = teamcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.playYear
     *
     * @return the value of nba_player.playYear
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public Integer getPlayyear() {
        return playyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.playYear
     *
     * @param playyear the value for nba_player.playYear
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setPlayyear(Integer playyear) {
        this.playyear = playyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.jerseyNo
     *
     * @return the value of nba_player.jerseyNo
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getJerseyno() {
        return jerseyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.jerseyNo
     *
     * @param jerseyno the value for nba_player.jerseyNo
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setJerseyno(String jerseyno) {
        this.jerseyno = jerseyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.teamNameEn
     *
     * @return the value of nba_player.teamNameEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getTeamnameen() {
        return teamnameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.teamNameEn
     *
     * @param teamnameen the value for nba_player.teamNameEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setTeamnameen(String teamnameen) {
        this.teamnameen = teamnameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.draft
     *
     * @return the value of nba_player.draft
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public Integer getDraft() {
        return draft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.draft
     *
     * @param draft the value for nba_player.draft
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setDraft(Integer draft) {
        this.draft = draft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.displayNameEn
     *
     * @return the value of nba_player.displayNameEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getDisplaynameen() {
        return displaynameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.displayNameEn
     *
     * @param displaynameen the value for nba_player.displayNameEn
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setDisplaynameen(String displaynameen) {
        this.displaynameen = displaynameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.birthDayStr
     *
     * @return the value of nba_player.birthDayStr
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getBirthdaystr() {
        return birthdaystr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.birthDayStr
     *
     * @param birthdaystr the value for nba_player.birthDayStr
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setBirthdaystr(String birthdaystr) {
        this.birthdaystr = birthdaystr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.heightValue
     *
     * @return the value of nba_player.heightValue
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public BigDecimal getHeightvalue() {
        return heightvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.heightValue
     *
     * @param heightvalue the value for nba_player.heightValue
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setHeightvalue(BigDecimal heightvalue) {
        this.heightvalue = heightvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.position
     *
     * @return the value of nba_player.position
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.position
     *
     * @param position the value for nba_player.position
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.age
     *
     * @return the value of nba_player.age
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.age
     *
     * @param age the value for nba_player.age
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_player.playerId
     *
     * @return the value of nba_player.playerId
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public String getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_player.playerId
     *
     * @param playerid the value for nba_player.playerId
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    public void setPlayerid(String playerid) {
        this.playerid = playerid;
    }
}