package com.alan.demo.entity;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.sid
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.st
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    private Integer st;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.sid
     *
     * @return the value of stock.sid
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.sid
     *
     * @param sid the value for stock.sid
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.st
     *
     * @return the value of stock.st
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    public Integer getSt() {
        return st;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.st
     *
     * @param st the value for stock.st
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    public void setSt(Integer st) {
        this.st = st;
    }
}