package com.alan.demo.mapper;

import com.alan.demo.entity.NbaPlayer;
import java.util.List;

public interface NbaPlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_player
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_player
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    int insert(NbaPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_player
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    NbaPlayer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_player
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    List<NbaPlayer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_player
     *
     * @mbg.generated Wed Mar 04 23:28:29 CST 2020
     */
    int updateByPrimaryKey(NbaPlayer record);
}