package com.alan.demo.mapper;

import com.alan.demo.entity.Stock;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    Stock selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    List<Stock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Mon Mar 09 13:49:20 CST 2020
     */
    int updateByPrimaryKey(Stock record);
}